DROP DATABASE IF EXISTS urls;

CREATE DATABASE urls;

DROP USER IF EXISTS 'user'@'%';
CREATE USER 'user'@'%' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON urls.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE urls;

CREATE TABLE url(
    id INT AUTO_INCREMENT PRIMARY KEY,
    long_url VARCHAR(2048) NOT NULL,
    short_url VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


