INSTALL PLUGIN group_replication SONAME 'group_replication.so';

DROP DATABASE IF EXISTS urls;

CREATE DATABASE urls;

DROP USER IF EXISTS 'user'@'%';

CREATE USER 'user'@'%' IDENTIFIED BY 'pass';

GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user'@'%';

GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;

GRANT CLONE_ADMIN, CONNECTION_ADMIN, CREATE USER, EXECUTE, FILE, 
      GROUP_REPLICATION_ADMIN, PERSIST_RO_VARIABLES_ADMIN, PROCESS, 
      RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, REPLICATION_APPLIER, 
      REPLICATION_SLAVE_ADMIN, ROLE_ADMIN, SELECT, SHUTDOWN, 
      SYSTEM_VARIABLES_ADMIN 
ON *.* TO 'user'@'%' WITH GRANT OPTION;

GRANT DELETE, INSERT, UPDATE 
ON mysql.* TO 'user'@'%' WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
      CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, 
      REFERENCES, SHOW VIEW, TRIGGER, UPDATE 
ON mysql_innodb_cluster_metadata.* TO 'user'@'%' WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
      CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, 
      REFERENCES, SHOW VIEW, TRIGGER, UPDATE 
ON mysql_innodb_cluster_metadata_bkp.* TO 'user'@'%' WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
      CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, 
      REFERENCES, SHOW VIEW, TRIGGER, UPDATE 
ON mysql_innodb_cluster_metadata_previous.* TO 'user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

USE urls;

CREATE TABLE url(
    id INT AUTO_INCREMENT PRIMARY KEY,
    long_url VARCHAR(2048) NOT NULL,
    short_url VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);