// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	port "github.com/matheusapostulo/url-shortener/internal/url/port"
	mock "github.com/stretchr/testify/mock"
)

// RedirectURLUsecase is an autogenerated mock type for the RedirectURLUsecase type
type RedirectURLUsecase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *RedirectURLUsecase) Execute(input port.RedirectURLInputDto) (port.RedirectURLOutputDto, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 port.RedirectURLOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(port.RedirectURLInputDto) (port.RedirectURLOutputDto, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(port.RedirectURLInputDto) port.RedirectURLOutputDto); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(port.RedirectURLOutputDto)
	}

	if rf, ok := ret.Get(1).(func(port.RedirectURLInputDto) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRedirectURLUsecase creates a new instance of RedirectURLUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedirectURLUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedirectURLUsecase {
	mock := &RedirectURLUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
