// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLShortener is an autogenerated mock type for the URLShortener type
type URLShortener struct {
	mock.Mock
}

// ShortenURL provides a mock function with given fields: id
func (_m *URLShortener) ShortenURL(id int) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLShortener creates a new instance of URLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLShortener {
	mock := &URLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
